title: Ian McDonald
baseurl: "/"
url: "http://ianmcdonald.ca"
markdown: kramdown
permalink: :title
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
