title: Ian McDonald
description: >-

baseurl: "/"
url: "https://ianmcdonald.ca"

markdown: kramdown
permalink: :title
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
